# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hardik Goel
tagline:          'Computer Scientist | Graduate Student'
description:      'Computer Scientist & Graduate Student <br /><br />
    <a href="https://github.com/goelhardik" target="_blank">github</a>.<a href="https://twitter.com/virtualbaba" target="_blank">twitter</a>.<a href="https://www.facebook.com/hardik.goel.549" target="_blank">facebook</a>'
url:              http://github.com/goelhardik
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/goelhardik
